### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShNadi** [ArtLabss/open-data-anonymizer#3]
Hi, 
while calling the anonymize function:
- anonym.anonymize(inplace = False, seed = 100)
I face with the following error:
- AttributeError: 'function' object has no attribute 'seed'

could you please let me know, how can I fix this error?
Thanks, Shiva

**Comment by shukkkur** [comment]
@ShNadi  Heyyy, many thanks for reporting the issue! Seems like I haven't uploaded the latest version to pypi (`pip`).
So, what you have to do: 
1. `pip install anonympy --upgrade` 
2. To verify:
```
import anonympy 
print(anonympy.__version__)
>>> 0.2.6
After that you can run your code with `seed` argument to get reproducible results.

**Comment by ShNadi** [comment]
> 

@shukkkur thanks for your quick reply! I have upgraded the anonympy to version 0.2.6 but, the problem is not solved. The same error as before...

Best,

**Comment by shukkkur** [comment]
@ShNadi  Can you plase share your code

**Comment by ShNadi** [comment]
![image](https://user-images.githubusercontent.com/44059592/160258404-86dd2fdf-ba2b-4e2b-a6ff-ba5fcb14094b.png)


>

**Comment by ShNadi** [comment]
@shukkkur Here is the code and the error...
Have a nice weekend!
![image](https://user-images.githubusercontent.com/44059592/160258457-b7790c86-736b-4cc6-b4a4-852a1443155e.png)

**Comment by shukkkur** [comment]
Tested both on my machine and Google Colab. Works.
![image](https://user-images.githubusercontent.com/78250180/160270987-b4b00736-5b5f-4014-a2d3-c42c92ca2a86.png)
![image](https://user-images.githubusercontent.com/78250180/160270999-f099b584-0ebe-4593-b89d-eee809a04185.png)

I would suggest to reinstall the package: 
1) `pip uninstall anonympy` 
2) `pip install anonympy`

**Comment by shukkkur** [comment]
@ShNadi  Any Updates?

**Comment by ShNadi** [comment]
hey @shukkkur,
I reinstalled it in my Jupyter notebook, and it still does not work. But it works perfectly in the Pycharm environment. So, probably there is something wrong with my Jupyter...
Many thanks for the nice implemented package and the support.
Best,
